CREATE TABLE IF NOT EXISTS soil_series (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_feature_id INTEGER NOT NULL UNIQUE,
  ldd_soil25_id INTEGER,
  ldd_wgs84_id INTEGER,
  soil_series_name TEXT NOT NULL,
  soil_series_code TEXT,
  soil_group TEXT,
  texture TEXT,
  fertility TEXT,
  ph_top TEXT,
  district TEXT,
  district_code TEXT,
  province TEXT DEFAULT 'นครปฐม',
  area_sqm NUMERIC,
  area_rai NUMERIC,
  geometry JSONB NOT NULL,
  raw_properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'Land Development Department (LDD), Thailand',
  source_dataset TEXT NOT NULL DEFAULT 'Soil Series, Nakhon Pathom',
  production_year_be INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE soil_series ADD COLUMN IF NOT EXISTS ldd_soil25_id INTEGER;
ALTER TABLE soil_series ADD COLUMN IF NOT EXISTS ldd_wgs84_id INTEGER;

CREATE INDEX IF NOT EXISTS soil_series_district_idx ON soil_series (district);
CREATE INDEX IF NOT EXISTS soil_series_name_idx ON soil_series (soil_series_name);
CREATE INDEX IF NOT EXISTS soil_series_group_idx ON soil_series (soil_group);
CREATE INDEX IF NOT EXISTS soil_series_geometry_gin_idx ON soil_series USING GIN (geometry);

ALTER TABLE soil_series ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "soil_series_public_read" ON soil_series;
CREATE POLICY "soil_series_public_read"
  ON soil_series
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT SELECT ON soil_series TO anon, authenticated;
