CREATE TABLE IF NOT EXISTS public.visitor_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  path TEXT,
  referrer TEXT,
  user_agent TEXT,
  ip_hash TEXT,
  ip_prefix TEXT,
  country_code TEXT,
  country_name TEXT,
  region TEXT,
  city TEXT,
  timezone TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  source TEXT NOT NULL DEFAULT 'netlify'
);

CREATE INDEX IF NOT EXISTS idx_visitor_events_occurred_at
  ON public.visitor_events (occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_visitor_events_country_region
  ON public.visitor_events (country_code, region, occurred_at DESC);

ALTER TABLE public.visitor_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admin read visitor_events" ON public.visitor_events;
CREATE POLICY "Admin read visitor_events" ON public.visitor_events
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = auth.uid()
        AND p.role = 'admin'
    )
  );
