import {
  DashboardOutlined,
  EnvironmentOutlined,
  SearchOutlined,
  CalculatorOutlined,
  BookOutlined,
  AuditOutlined,
  CommentOutlined,
  ReadOutlined,
} from '@ant-design/icons';

export const landingToolsCatalog = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    subtitle: 'ภาพรวมข้อมูล',
    Icon: DashboardOutlined,
    href: '/dashboard',
    isInternal: true,
  },
  {
    id: 'smart-map',
    title: 'Smart Map',
    subtitle: 'แผนที่เกษตรกร',
    Icon: EnvironmentOutlined,
    href: '/smart-map',
    isInternal: true,
  },
  {
    id: 'search',
    title: 'ค้นหาข้อมูล',
    subtitle: 'ฐานข้อมูลเกษตร',
    Icon: SearchOutlined,
    href: '/dashboard/search',
    isInternal: true,
  },
  {
    id: 'crop-cost-lab',
    title: 'Crop Cost Lab',
    subtitle: 'คำนวณต้นทุนพืช',
    Icon: CalculatorOutlined,
    href: 'https://agrilabcost-ai.vercel.app/',
    isExternal: true,
  },
  {
    id: 'knowledge-hub',
    title: 'คลังความรู้',
    subtitle: 'บทความ/คู่มือ',
    Icon: BookOutlined,
    href: 'https://kasetinfo.netlify.app/',
    isExternal: true,
  },
  {
    id: 'evaluation',
    title: 'ระบบประเมิน',
    subtitle: 'ประเมินเว็บไซต์',
    Icon: AuditOutlined,
    isModalTrigger: true,
    modalKey: 'websiteEvaluation',
  },
  {
    id: 'farmer-forum',
    title: 'Farmer Forum',
    subtitle: 'ชุมชนเกษตรกร',
    Icon: CommentOutlined,
    href: '/dashboard/community/forum',
    isInternal: true,
  },
  {
    id: 'user-manual',
    title: 'คู่มือการใช้งาน',
    subtitle: 'เอกสาร/วีดีโอ',
    Icon: ReadOutlined,
    href: '/manual',
    isInternal: true,
  },
  {
    id: 'admin-manual',
    title: 'คู่มือการใช้งาน',
    subtitle: 'ผู้ดูแลระบบ',
    Icon: ReadOutlined,
    href: '/manual',
    isInternal: true,
  },
];
