export const EMPTY_AREA_SELECTION = {
  level: 'province',
  provinceCode: '73',
  provinceName: 'นครปฐม',
  districtCode: null,
  districtName: null,
  subdistrictCode: null,
  subdistrictName: null,
};

export const SMART_MAP_LAYERS = [
  {
    id: 'agricultural_area',
    label: 'พื้นที่เกษตร',
    group: 'area_register',
    geometryType: 'choropleth',
    sourceTable: 'agricultural_areas',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: true,
    availability: 'active',
    publicFields: [],
  },
  {
    id: 'learning_centers',
    label: 'ศพก.',
    group: 'farmer_networks',
    geometryType: 'point',
    sourceTable: 'learning_centers',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'active',
    coordinateType: 'lat_lon',
    coordinateJsonField: 'custom_fields',
    latitudeField: 'latitude',
    longitudeField: 'longitude',
    publicFields: [
      'id',
      'name',
      'district',
      'subdistrict',
      'featured_product',
      'knowledge_course',
    ],
  },
  {
    id: 'young_farmer_groups',
    label: 'กลุ่มยุวเกษตรกร',
    group: 'farmer_networks',
    geometryType: 'point',
    sourceTable: 'young_farmer_groups_detailed',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'active',
    coordinateType: 'lat_lon',
    latitudeField: 'lat',
    longitudeField: 'lon',
    publicFields: [
      'id',
      'data_year',
      'group_name',
      'district',
      'subdistrict',
      'member_count',
      'activity',
      'lat',
      'lon',
      'updated_at',
    ],
  },
  {
    id: 'career_groups',
    label: 'กลุ่มส่งเสริมอาชีพการเกษตร',
    group: 'farmer_networks',
    geometryType: 'point',
    sourceTable: 'agricultural_career_groups',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'active',
    coordinateType: 'lat_lon',
    latitudeField: 'lat',
    longitudeField: 'lon',
    publicFields: [
      'id',
      'data_year',
      'group_name',
      'district',
      'subdistrict',
      'member_count',
      'activity',
      'potential_level',
      'lat',
      'lon',
      'updated_at',
    ],
  },
  {
    id: 'housewife_groups',
    label: 'กลุ่มแม่บ้านเกษตรกร',
    group: 'farmer_networks',
    geometryType: 'point',
    sourceTable: 'housewife_farmer_groups',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'active',
    coordinateType: 'lat_lon',
    latitudeField: 'lat',
    longitudeField: 'lon',
    publicFields: [
      'id',
      'year',
      'group_name',
      'district',
      'subdistrict',
      'member_count',
      'activity',
      'production_standard',
      'potential_level',
      'lat',
      'lon',
      'updated_at',
    ],
  },
  {
    id: 'forecast_plots',
    label: 'แปลงพยากรณ์',
    group: 'production',
    geometryType: 'point',
    sourceTable: 'forecast_plots',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'active',
    coordinateType: 'utm_47n',
    latitudeField: 'coord_x',
    longitudeField: 'coord_y',
    publicFields: [
      'id',
      'district',
      'subdistrict',
      'crop_type',
      'variety',
      'planted_area_rai',
      'plot_type',
      'crop_status',
      'coord_x',
      'coord_y',
      'updated_at',
    ],
  },
  {
    id: 'fire_hotspots',
    label: 'จุดความร้อน',
    group: 'risk',
    geometryType: 'point',
    sourceTable: 'fire_hotspots',
    sourceLabel: 'GISTDA',
    defaultVisible: false,
    availability: 'active',
    coordinateType: 'lat_lon',
    latitudeField: 'latitude',
    longitudeField: 'longitude',
    publicFields: [
      'id',
      'acq_date',
      'acq_time',
      'confidence',
      'frp',
      'district',
      'subdistrict',
      'latitude',
      'longitude',
      'updated_at',
    ],
  },
  {
    id: 'soil_series',
    label: 'ชุดดิน',
    group: 'natural_resources',
    geometryType: 'polygon',
    sourceTable: 'soil_series',
    sourceLabel: 'กรมพัฒนาที่ดิน',
    defaultVisible: false,
    availability: 'active',
    publicFields: [
      'id',
      'soil_series_name',
      'soil_series_code',
      'soil_group',
      'texture',
      'fertility',
      'ph_top',
      'district',
      'area_rai',
      'geometry',
      'updated_at',
    ],
  },
  {
    id: 'agri_tourism',
    label: 'ท่องเที่ยวเกษตร',
    group: 'farmer_networks',
    geometryType: 'point',
    sourceTable: 'agri_tourism',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'coordinate_incomplete',
    coordinateType: 'lat_lon',
    latitudeField: 'latitude',
    longitudeField: 'longitude',
    publicFields: [
      'id',
      'spot_name',
      'district',
      'spot_type',
      'latitude',
      'longitude',
      'updated_at',
    ],
  },
  {
    id: 'gis_areas',
    label: 'พื้นที่ GIS',
    group: 'area_register',
    geometryType: 'point',
    sourceTable: 'gis_areas',
    sourceLabel: 'สำนักงานเกษตรจังหวัดนครปฐม',
    defaultVisible: false,
    availability: 'empty',
    coordinateType: 'lat_lon',
    latitudeField: 'latitude',
    longitudeField: 'longitude',
    publicFields: [
      'id',
      'area_name',
      'district',
      'latitude',
      'longitude',
      'updated_at',
    ],
  },
];

export function getSmartMapLayer(id) {
  return SMART_MAP_LAYERS.find((layer) => layer.id === id) || null;
}
