create table if not exists public.tbk_cultivation_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default current_date,
  scraped_at timestamptz not null default now(),
  data_year integer not null,
  group_code text not null,
  group_name text not null,
  location_code text not null,
  location_name text not null,
  item_breed text not null,
  household_count integer not null check (household_count >= 0),
  plot_count integer not null check (plot_count >= 0),
  area_rai numeric(14, 2) not null check (area_rai >= 0),
  disaster_household_count integer not null check (disaster_household_count >= 0),
  disaster_plot_count integer not null check (disaster_plot_count >= 0),
  disaster_area_rai numeric(14, 2) not null check (disaster_area_rai >= 0),
  remaining_area_rai numeric(14, 2) not null check (remaining_area_rai >= 0),
  unique (snapshot_date, data_year, group_code, location_code, item_breed)
);

create index if not exists tbk_cultivation_latest_idx
  on public.tbk_cultivation_snapshots (data_year, snapshot_date desc, group_code);

alter table public.tbk_cultivation_snapshots enable row level security;

grant select on public.tbk_cultivation_snapshots to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on public.tbk_cultivation_snapshots from anon, authenticated;

drop policy if exists "TBK cultivation snapshots are readable"
  on public.tbk_cultivation_snapshots;

create policy "TBK cultivation snapshots are readable"
  on public.tbk_cultivation_snapshots for select
  to anon, authenticated using (true);
