create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  endpoint text not null,
  subscription jsonb not null,
  outbreak boolean not null default true,
  hotspot boolean not null default true,
  districts text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create table if not exists public.push_alert_events (
  event_key text primary key,
  event_type text not null check (event_type in ('outbreak', 'hotspot')),
  district text,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
alter table public.push_alert_events enable row level security;

grant select, insert, update, delete on public.push_subscriptions to authenticated;
grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;
grant all on public.push_subscriptions to service_role;
grant all on public.push_alert_events to service_role;

create policy "Users manage their push subscriptions"
on public.push_subscriptions for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create index if not exists push_subscriptions_user_id_idx
on public.push_subscriptions (user_id);;
