create table if not exists public.rice_harvest_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default current_date,
  scraped_at timestamptz not null default now(),
  source_cutoff_date date,
  crop_year text not null,
  district_code text not null,
  district text not null,
  harvest_month smallint not null check (harvest_month between 1 and 12),
  household_count integer not null check (household_count >= 0),
  plot_count integer not null check (plot_count >= 0),
  area_rai numeric(14, 2) not null check (area_rai >= 0),
  estimated_tons numeric(16, 6) not null check (estimated_tons >= 0),
  unique (snapshot_date, crop_year, district_code, harvest_month)
);

create index if not exists rice_harvest_latest_idx
  on public.rice_harvest_snapshots (crop_year, snapshot_date desc, harvest_month, district_code);

alter table public.rice_harvest_snapshots enable row level security;

grant select on public.rice_harvest_snapshots to anon, authenticated;

drop policy if exists "Rice harvest snapshots are readable"
  on public.rice_harvest_snapshots;

create policy "Rice harvest snapshots are readable"
  on public.rice_harvest_snapshots for select
  to anon, authenticated using (true);
